### ISSUE TITLE
%arrow2% does not work

### ISSUE THREAD

**Issue by Dungjava** [RefracDevelopment/SimpleStaffChat2#10]
Hello 
![image](https://user-images.githubusercontent.com/99890979/175760053-43cc17a2-de9d-4696-b37e-3663fb54ec3b.png)

**Comment by Refrac** [comment]
@Dungjava What minecraft version and is it spigot or bungeecord?

**Comment by Refrac** [comment]
I'll release a quick fix for that actually

**Comment by Refrac** [comment]
All you need to do is re-download the jar and it should work now.
