### ISSUE TITLE
RGB not working in latest update

### ISSUE THREAD

**Issue by ccyounga** [RefracDevelopment/SimpleStaffChat2#11]
Greetings. I'm talking about a recent update.
I am using the latest plugin version 2.3. Paper server core 1.18.2.
RGB color is not displayed, the numbers remain and are not defined.
I dare to assume that you have your own method of supporting RGB, although I do not know why you did this. Your plugin does not create new groups, they are created by luckperms and it determines the name for them either by him or by another, for example, tab premium. I'm using the tab premium plugin to display the normal group name, since this name should be displayed in the panel on the tab key. Based on this logic, your plugin should handle any request for a color in the format XXXXXX or #XXXXXX. In the case of tab premium, it works using brackets and arrows {#XXXXXX>}[Group_name]{#XXXXXX<}. I ask you to adapt the work of RGB for other plugins.

**Comment by Refrac** [comment]
I will not be attempting to change this as all plugins have a different format for RGB/HEX colors.
