### ISSUE TITLE
Discord Issue

### ISSUE THREAD

**Issue by CroaBeast** [RefracDevelopment/SimpleStaffChat2#3]
Hi, the discord link doesn't work.
I want to ask if there is a way to have support for PlaceholderAPI placeholders on the bungee version.
Or maybe a work-around to get placeholders work between servers.

**Comment by Refrac** [comment]
> Hi, the discord link doesn't work. I want to ask if there is a way to have support for PlaceholderAPI placeholders on the bungee version. Or maybe a work-around to get placeholders work between servers.

PlaceholderAPI does not support BungeeCord so that would not be possible although i would be able to add placeholders for certain plugins such as LuckPerms.
