### ISSUE TITLE
Color picker support

### ISSUE THREAD

**Issue by ccyounga** [RefracDevelopment/SimpleStaffChat2#4]
Need to add support for RGB color palette. The same tab premium plugin supports any color, but we cannot display the placeholder in this plugin for the chat for the administration, since it does not accept six color characters.

**Comment by Refrac** [comment]
> Need to add support for RGB color palette. The same tab premium plugin supports any color, but we cannot display the placeholder in this plugin for the chat for the administration, since it does not accept six color characters.

This can be looked into although i have had many issues when trying to support RGB/HEX colors.

**Comment by Refrac** [comment]
@ccyounga This has been added in update 2.3: https://www.spigotmc.org/resources/simplestaffchat2-1-7-1-19.91883/update?update=461893
