### ISSUE TITLE
Player can get stuck in staff-chat if not careful

### ISSUE THREAD

**Issue by TheJoshue** [RefracDevelopment/SimpleStaffChat2#7]
I recommend creating "SSCChatEvent" which will basically trigger on every message that is sent in staff chat channel.

Why this will be useful?
If player has permission to toggle his channel from public to staff, he does it
Now he chats for some time.
Now let's imagine he was abusing and there comes moderator/administrator and demotes him
Now he loses permission to USE + SEE staff chat, while he still has staff chat toggled - he is basically stuck in channel, he can chat but will never see neither his own not other's messages from staff channel, but he can't chat in public chat (he can after server restart)

if we create "SSCChatEvent" which will trigger only on every message that has been successfully sent to staff channel, then we can listen to that event
When that event happens, we check message sender's permission to USE (and maybe SEE permission too?) simplestaffchat.

If he doesn't have it, after he has sent 1 message while being stuck in staff channel, he will be notified with custom configurable message that his staff chat mode has been deactivated and now he's put to public chat as needed.
Of course when this happens plugin will automatically change his mode to get out of staff chat.

Hope this is useful!

**Comment by Refrac** [comment]
I'll just add permission checks to the event itself no need for a new event.

**Comment by Refrac** [comment]
This has been released: https://www.spigotmc.org/resources/simplestaffchat2-1-7-1-19.91883/update?update=461703
